//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsyscomEntities : DbContext
    {
        public bdsyscomEntities()
            : base("name=bdsyscomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actualizaciones> Actualizaciones { get; set; }
        public virtual DbSet<cActivo> cActivo { get; set; }
        public virtual DbSet<cEstatus> cEstatus { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<recepcion> recepcion { get; set; }
        public virtual DbSet<soporte> soporte { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
    }
}
